server:
  port: 8092

spring:
  application:
    name: notification

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8090/eureka'
  instance:
    hostname: localhost

reservation:
  api:
    url:
      authuser: 'http://localhost:8091/authusers'