server:
  port: 8080

spring:
  application:
    name: api-getway
  cloud:
    gateway:
      routes:
        - id: authuser-ead
          uri: lb://AUTHUSER-SERVICE
          predicates:
            - Path=/authuser/**
        - id: notification-ead
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8090/eureka/'
  instance:
    hostname: localhost

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG