server:
  port: 8081
  servlet:
    context-path: /authuser

spring:
  application:
    name: authuser-service

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8090/eureka/'
  instance:
    hostname: localhost

reservation:
  api:
    url:
      authuser: 'http://notification-service/notification/api/iam'

