server:
  port: 8091

spring:
  application:
    name: authouser

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8090/eureka'
  instance:
    hostname: localhost

reservation:
  api:
    url:
      notification: 'http://localhost:8092/notifications'
